### ISSUE TITLE
Would it make more sense to make RocksDB a table AM instead of a FDW?

### ISSUE THREAD

**Issue by davidfetter** [vidardb/PostgresForeignDataWrapper#25]
https://www.postgresql.org/docs/devel/tableam.html

**Comment by jsc0218** [comment]
Hi David, thanks for coming here and giving suggestion. One hesitation for me to use AM instead of FDW, (please confirm it is true or not), AM has to store all data in table instead of all in index. We wish we can put all data in the index. Otherwise, AM method is more promising for us.

**Comment by jsc0218** [comment]
Hi David, thanks for coming here and giving suggestion. One hesitation for
me to use AM instead of FDW, (please confirm it is true or not), I have to
store all data in table instead of all in index. We wish we can put all
data in the index. Otherwise, AM method is more promising for us.

**Comment by davidfetter** [comment]
Thanks for getting back to me on this. There are also index AMs. If you want to store the data in indexes, they might be a good fit. https://www.postgresql.org/docs/devel/indexam.html

**Comment by jsc0218** [comment]
Cool! Seems exactly what we need! I will carefully read the doc. Appreciated.

**Comment by jsc0218** [comment]
After reading the doc and related presentations as well as ZomboDB's implementation, I finally figure out the exact difference between table AM, index AM and FDW. The ultimate best choice for us should be table AM as you suggested. But we will wait for more table AM implementations and then do the migration.
