### ISSUE TITLE
Drop database fails because of the worker process

### ISSUE THREAD

**Issue by nadbp** [vidardb/PostgresForeignDataWrapper#32]
The error message is as shown in the attachment. The worker process is still accessing the database, so DROP database fails.

![drop](https://user-images.githubusercontent.com/7585859/84612060-71bc2980-ae8d-11ea-9cb4-720c303305d7.JPG)

**Comment by jsc0218** [comment]
We probably will do a trigger to solve this issue. Keep this issue open until we solve it.

**Comment by chenquanzhao** [comment]
@nadbp  The issue has been fixed and please try the latest release package.
